openapi: 3.0.0
info:
  title: Diagonal API
  version: 1.0.0
  description: Simple API documentation for Diagonal API
paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: OK
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: OK
